language: csharp
mono: none
dotnet: 2.2.103
script:
  - dotnet tool install -g Wyam.Tool
# install:
# - dotnet tool install -g Wyam.Tool
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: _site
#   target_branch: master
#   on:
#     branch: source